# Generated by Django 2.2.3 on 2019-08-02 04:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='room_category_images/%Y/%m/%d')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_category', to='scenery.RoomCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('room_image', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d')),
                ('room_image2', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d')),
                ('room_image3', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d')),
                ('room_image4', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d')),
                ('room_image5', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d')),
                ('room_image6', models.ImageField(blank=True, null=True, upload_to='room_images/%Y/%m/%d')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='scenery.RoomCategory')),
            ],
        ),
    ]
