# Generated by Django 2.2.3 on 2019-08-02 05:01

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('scenery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Scenery',
        ),
        migrations.RenameModel(
            old_name='RoomCategory',
            new_name='SceneryCategory',
        ),
    ]
