# Generated by Django 2.2.3 on 2019-08-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Appointment',
        ),
    ]
