# Generated by Django 2.2.3 on 2019-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190801_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
