# Generated by Django 2.2.3 on 2019-08-01 07:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_title', models.CharField(max_length=30)),
                ('information_text', ckeditor.fields.RichTextField()),
                ('information_image', models.ImageField(blank=True, null=True, upload_to='information_images/%Y/%m/%d')),
            ],
        ),
    ]
