# Generated by Django 2.2.3 on 2019-08-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='information_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
